# Generated by Django 3.0.2 on 2020-01-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastosFixos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('categoria', models.CharField(max_length=140)),
                ('val_esperado', models.FloatField()),
                ('val_pago', models.FloatField()),
            ],
        ),
    ]
