# Generated by Django 3.0.2 on 2020-01-03 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('categoria', models.CharField(max_length=140)),
                ('val_esperado', models.FloatField(verbose_name='Valor Esperado')),
                ('val_pago', models.FloatField(verbose_name='Valor Pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GastosFixos',
        ),
    ]
