# Generated by Django 2.2.9 on 2020-01-06 20:25

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0002_auto_20200103_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixo',
            name='user',
        ),
        migrations.AddField(
            model_name='fixo',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
